/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R401kRouteImport } from './routes/401k'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoveragesRouteImport } from './routes/coverages'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as HrRouteImport } from './routes/hr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as PortalCardsRouteImport } from './routes/_portal/cards'
import { Route as PortalClaimsRouteImport } from './routes/_portal/claims'
import { Route as PortalCoverageRouteImport } from './routes/_portal/coverage'
import { Route as PortalDocumentsRouteImport } from './routes/_portal/documents'
import { Route as PortalMessagesRouteImport } from './routes/_portal/messages'
import { Route as PortalPortalRouteImport } from './routes/_portal/portal'
import { Route as PortalProfileRouteImport } from './routes/_portal/profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R401kRoute = R401kRouteImport.update({
  id: '/401k',
  path: '/401k',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoveragesRoute = CoveragesRouteImport.update({
  id: '/coverages',
  path: '/coverages',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCardsRoute = PortalCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClaimsRoute = PortalClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCoverageRoute = PortalCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalRoute = PortalPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401k': typeof R401kRoute
  '/about': typeof AboutRoute
  '/coverages': typeof CoveragesRoute
  '/funding': typeof FundingRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
  '/videos': typeof VideosRoute
  '/cards': typeof PortalCardsRoute
  '/claims': typeof PortalClaimsRoute
  '/coverage': typeof PortalCoverageRoute
  '/documents': typeof PortalDocumentsRoute
  '/messages': typeof PortalMessagesRoute
  '/portal': typeof PortalPortalRoute
  '/profile': typeof PortalProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401k': typeof R401kRoute
  '/about': typeof AboutRoute
  '/coverages': typeof CoveragesRoute
  '/funding': typeof FundingRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
  '/videos': typeof VideosRoute
  '/cards': typeof PortalCardsRoute
  '/claims': typeof PortalClaimsRoute
  '/coverage': typeof PortalCoverageRoute
  '/documents': typeof PortalDocumentsRoute
  '/messages': typeof PortalMessagesRoute
  '/portal': typeof PortalPortalRoute
  '/profile': typeof PortalProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/401k': typeof R401kRoute
  '/_portal': typeof PortalRouteWithChildren
  '/about': typeof AboutRoute
  '/coverages': typeof CoveragesRoute
  '/funding': typeof FundingRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
  '/videos': typeof VideosRoute
  '/_portal/cards': typeof PortalCardsRoute
  '/_portal/claims': typeof PortalClaimsRoute
  '/_portal/coverage': typeof PortalCoverageRoute
  '/_portal/documents': typeof PortalDocumentsRoute
  '/_portal/messages': typeof PortalMessagesRoute
  '/_portal/portal': typeof PortalPortalRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401k'
    | '/about'
    | '/coverages'
    | '/funding'
    | '/hr'
    | '/login'
    | '/payroll'
    | '/quote'
    | '/services'
    | '/technology'
    | '/videos'
    | '/cards'
    | '/claims'
    | '/coverage'
    | '/documents'
    | '/messages'
    | '/portal'
    | '/profile'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401k'
    | '/about'
    | '/coverages'
    | '/funding'
    | '/hr'
    | '/login'
    | '/payroll'
    | '/quote'
    | '/services'
    | '/technology'
    | '/videos'
    | '/cards'
    | '/claims'
    | '/coverage'
    | '/documents'
    | '/messages'
    | '/portal'
    | '/profile'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/401k'
    | '/_portal'
    | '/about'
    | '/coverages'
    | '/funding'
    | '/hr'
    | '/login'
    | '/payroll'
    | '/quote'
    | '/services'
    | '/technology'
    | '/videos'
    | '/_portal/cards'
    | '/_portal/claims'
    | '/_portal/coverage'
    | '/_portal/documents'
    | '/_portal/messages'
    | '/_portal/portal'
    | '/_portal/profile'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R401kRoute: typeof R401kRoute
  PortalRoute: typeof PortalRouteWithChildren
  AboutRoute: typeof AboutRoute
  CoveragesRoute: typeof CoveragesRoute
  FundingRoute: typeof FundingRoute
  HrRoute: typeof HrRoute
  LoginRoute: typeof LoginRoute
  PayrollRoute: typeof PayrollRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  TechnologyRoute: typeof TechnologyRoute
  VideosRoute: typeof VideosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401k': {
      id: '/401k'
      path: '/401k'
      fullPath: '/401k'
      preLoaderRoute: typeof R401kRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverages': {
      id: '/coverages'
      path: '/coverages'
      fullPath: '/coverages'
      preLoaderRoute: typeof CoveragesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/cards': {
      id: '/_portal/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof PortalCardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/claims': {
      id: '/_portal/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof PortalClaimsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/coverage': {
      id: '/_portal/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof PortalCoverageRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/documents': {
      id: '/_portal/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/messages': {
      id: '/_portal/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal': {
      id: '/_portal/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalPortalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalCardsRoute: typeof PortalCardsRoute
  PortalClaimsRoute: typeof PortalClaimsRoute
  PortalCoverageRoute: typeof PortalCoverageRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalPortalRoute: typeof PortalPortalRoute
  PortalProfileRoute: typeof PortalProfileRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCardsRoute: PortalCardsRoute,
  PortalClaimsRoute: PortalClaimsRoute,
  PortalCoverageRoute: PortalCoverageRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalPortalRoute: PortalPortalRoute,
  PortalProfileRoute: PortalProfileRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R401kRoute: R401kRoute,
  PortalRoute: PortalRouteWithChildren,
  AboutRoute: AboutRoute,
  CoveragesRoute: CoveragesRoute,
  FundingRoute: FundingRoute,
  HrRoute: HrRoute,
  LoginRoute: LoginRoute,
  PayrollRoute: PayrollRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  TechnologyRoute: TechnologyRoute,
  VideosRoute: VideosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
